// Content / i18n strings for erdm.io
window.CONTENT = {
  en: {
    nav: [
      { id: "intro", label: "Intro" },
      { id: "about", label: "About" },
      { id: "experience", label: "Experience" },
      { id: "projects", label: "Projects" },
      { id: "stack", label: "Stack" },
      { id: "education", label: "Education" },
      { id: "playground", label: "Playground" },
      { id: "writing", label: "Writing" },
      { id: "contact", label: "Contact" },
    ],
    hero: {
      role: "Full-stack engineer · CTO @ Devredin · CS @ İYTE",
      tagline: "I build the quiet systems that run when no one's watching.",
      status: "Open to summer 2026 opportunities",
      cta1: "See my work",
      cta2: "Get in touch",
      foot1: "Based in İzmir · 38.41°N, 27.13°E",
      foot2: "Scroll",
      year: "VOL. 26 · ISSUE I",
    },
    about: {
      eyebrow: "About",
      h: "Mostly invisible work, on purpose.",
      p1: "I'm a third-year Computer Engineering student at İYTE and CTO at Devredin, Turkey's business-transfer marketplace. Most of what I do is invisible — Postgres replication, Cloudflare workers, AI tooling that runs in production. The good stuff is usually behind a server.",
      p2: "Outside work, I read database papers, organize Secret Santas for hundreds of engineering students, and plan road trips that have nothing to do with code.",
      facts: [
        { label: "Based in İzmir", icon: "pin" },
        { label: "Reading: DDIA, Ch. 3", icon: "book" },
        { label: "Cafés > dorm room", icon: "cup" },
        { label: "Speaks: TR · EN", icon: "globe" },
      ],
      caption: ["Fig. 01 — portrait, april '26", "İzmir · 35mm"],
    },
    exp: {
      eyebrow: "Experience",
      h: "What I've actually been building.",
      items: [
        {
          period: "2024 — Present",
          role: "Chief Technology Officer",
          where: "Devredin · İzmir",
          tags: ["infra", "ai", "data"],
          bullets: [
            "Lead all engineering at Turkey's business-transfer marketplace. Hold 2.5% equity.",
            "Migrated production from a legacy Nginx/Apache split to a hardened Debian + Nginx stack.",
            "Built mcp.devredin.com — an MCP server exposing platform data to internal AI tooling.",
            "Designed the AI-powered weekly business report generator and listing valuation module, grounded in 1,261+ active listings.",
            "Cut over the CDN to Cloudflare with image transformations, replacing BunnyCDN.",
            "Owned the EİDS Faz-2 commercial real estate integration with the Ministry of Trade.",
          ],
        },
        {
          period: "2025 — Present",
          role: "Co-founder · Engineer",
          where: "benzersor.com · stealth",
          tags: ["stealth", "co-founder"],
          bullets: [
            "Co-founded with 10% equity. Building quietly. Details under wraps until launch.",
          ],
        },
        {
          period: "2023 — 2024",
          role: "Freelance · Engineering",
          where: "Various · İzmir / Remote",
          tags: ["freelance", "full-stack"],
          bullets: [
            "Shipped full-stack work for early-stage Turkish teams — internal tools, dashboards, scheduled jobs.",
            "Picked up Cloudflare Workers and Postgres replication on the job; wrote the post-mortems my clients didn't.",
          ],
        },
      ],
    },
    proj: {
      eyebrow: "Selected projects",
      h: "Selected works",
      meta: "Six pieces · 2023 — present · scroll →",
      items: [
        {
          k: "MCP-01",
          title: "Devredin MCP Server",
          host: "mcp.devredin.com",
          desc: "One of the first production MCP deployments in Turkey. Exposes the marketplace database to internal AI tooling for analytics and ops.",
          stack: ["Node.js", "MCP", "PostgreSQL", "Cloudflare"],
          year: "'26",
        },
        {
          k: "RPT-02",
          title: "Weekly Business Report",
          host: "Devredin · internal",
          desc: "Editorial-quality reports generated weekly from raw marketplace data. LLMs grounded in SQL, no hallucinated numbers.",
          stack: ["Postgres", "LLM API", "Prompt orchestration"],
          year: "'25",
        },
        {
          k: "VAL-03",
          title: "Listing Valuation",
          host: "Devredin · production",
          desc: "Empirical valuation engine on 1,261+ active listings. Replaces gut-feel pricing with data, with confidence intervals shown to the user.",
          stack: ["Postgres", "TypeScript", "Statistics"],
          year: "'25",
        },
        {
          k: "MAP-04",
          title: "SiksokHarita",
          host: "İYTE · CENG 318 HCI",
          desc: "Real-time campus shuttle tracking. Live shuttle positions on a map, ETA estimates, route history. HCI course capstone.",
          stack: ["React", "Spring Boot", "PostgreSQL"],
          year: "'24",
        },
        {
          k: "SAN-05",
          title: "iyteyilbasi Secret Santa",
          host: "Community · İYTE",
          desc: "Built the matching platform. Paired 200+ engineering students for the New Year exchange — twice. Warm, festive, off-brand on purpose.",
          stack: ["Next.js", "Postgres", "Resend"],
          year: "'24",
        },
        {
          k: "BNZ-06",
          title: "benzersor.com",
          host: "stealth · 2026",
          desc: "Co-founded. The placeholder card you're looking at is more than I'm allowed to show. Talk soon.",
          stack: ["redacted"],
          year: "'26",
        },
      ],
    },
    stack: {
      eyebrow: "Tech",
      h: "How the kitchen is run.",
      categories: [
        { id: "lang", title: "Languages", items: [
          { name: "TypeScript", note: "Default. Most things start here." },
          { name: "Java", note: "Spring Boot work; mostly back-of-house at İYTE." },
          { name: "Python", note: "Scripts, scrapers, prompt orchestration." },
          { name: "SQL", note: "Postgres dialect. The most useful language I know." },
        ]},
        { id: "front", title: "Frontend", items: [
          { name: "React", note: "Comfortable. Boring. Predictable. Good." },
          { name: "Next.js", note: "App Router. RSC pragmatically, not religiously." },
          { name: "Tailwind", note: "Disagree with purists, ship faster anyway." },
        ]},
        { id: "back", title: "Backend", items: [
          { name: "Node.js", note: "Most of Devredin's API surface lives here." },
          { name: "Spring Boot", note: "Course work and one freelance project." },
          { name: "Prisma", note: "Schema as truth. Migrations I trust." },
        ]},
        { id: "data", title: "Data", items: [
          { name: "PostgreSQL", note: "Replication is what I'm studying for CENG 465 right now." },
          { name: "Redis", note: "Cache + queues. Not magic. Useful." },
        ]},
        { id: "infra", title: "Infra", items: [
          { name: "Debian", note: "Migrated Devredin from a legacy stack to this." },
          { name: "Nginx", note: "Reverse proxy of choice. Still." },
          { name: "Cloudflare", note: "CDN, Workers, Email Routing. The whole thing." },
          { name: "AWS Lightsail", note: "Cheap, predictable, gets out of the way." },
        ]},
        { id: "ai", title: "AI / Tooling", items: [
          { name: "MCP", note: "Built mcp.devredin.com. Early adopter, not zealot." },
          { name: "LLM APIs", note: "Anthropic, OpenAI. Grounded outputs only." },
          { name: "CodeRabbit", note: "Saves me from myself in PRs." },
        ]},
      ],
    },
    edu: {
      eyebrow: "Education",
      h: "Where the credentials come from.",
      school: "İzmir Institute of Technology",
      schoolEm: "İYTE",
      degree: "BSc, Computer Engineering — third year",
      gpa: [
        { label: "GPA", value: "3.93 / 4.00" },
        { label: "YKS Rank", value: "Top 2.6k of 3M" },
        { label: "Class of", value: "2027" },
      ],
      courses: [
        { code: "CENG 465", name: "Designing Data-Intensive Applications", term: "Spring '26" },
        { code: "CENG 318", name: "Human-Computer Interaction", term: "Fall '25" },
        { code: "MATH 313", name: "Cryptography", term: "Fall '25" },
        { code: "CENG 311", name: "Algorithms", term: "Spring '25" },
        { code: "CENG 222", name: "Statistical Methods for CS", term: "Fall '24" },
      ],
      learningLabel: "Currently learning",
      learning: [
        "Postgres logical replication",
        "Vector search with pgvector",
        "Linear's sync engine",
        "MCP server design patterns",
        "Cloudflare Durable Objects",
        "Probabilistic data structures",
        "Postgres logical replication",
      ],
    },
    playground: {
      eyebrow: "Playground",
      h: "A small workshop. Switch modes.",
      lede: "The editorial site dims and the page becomes a tool. Each module is a thing I made for myself first; you're welcome to poke them.",
      pulse: { title: "Live Devredin pulse", desc: "Sanitized snapshot from the MCP server. Refreshes hourly. Not a dashboard — a heartbeat.", foot: "Mocked for demo · last sync 14m ago" },
      val: { title: "Listing valuation toy", desc: "Type a category and revenue. The estimator returns a band, not a number. Educational, not a quote.", foot: "Built on 1,261 active listings · educational only" },
      repl: { title: "Postgres replication, visible", desc: "Primary commits, the WAL ships, the replica catches up. Lag is a feature you can see.", foot: "Tied to CENG 465 · idle lag avg 0.4s" },
      term: { title: "Terminal", desc: "Press ~ anywhere on the site to open. A few honest commands.", foot: "press tilde (~) to summon · esc to close" },
    },
    writing: {
      eyebrow: "Writing",
      h: "Notes, not a blog.",
      empty: "Currently empty by choice.",
      emptyDesc: "I'd rather have nothing here than have stale opinions about clean code. The first piece will land when I have something worth saying — likely about Postgres replication or the messier side of MCP.",
      cta: "Notify me",
    },
    contact: {
      bigTop: "Working on something",
      bigBottom: "I should know about?",
      email: "hi@erdm.io",
      socials: { gh: "github/erdmio", li: "linkedin/erdmio", tw: "x/erdmio" },
      colophon: "© 2026 · Built in İzmir · Set in Instrument Serif & Inter Tight · Hosted on Cloudflare",
      now: "Now: Postgres logical decoding",
    },
  },
  tr: {
    nav: [
      { id: "intro", label: "Giriş" },
      { id: "about", label: "Hakkında" },
      { id: "experience", label: "Tecrübe" },
      { id: "projects", label: "Projeler" },
      { id: "stack", label: "Yığın" },
      { id: "education", label: "Eğitim" },
      { id: "playground", label: "Atölye" },
      { id: "writing", label: "Yazılar" },
      { id: "contact", label: "İletişim" },
    ],
    hero: {
      role: "Full-stack mühendis · Devredin'de CTO · İYTE'de CS",
      tagline: "Kimsenin bakmadığı zamanlarda çalışan sessiz sistemleri kuruyorum.",
      status: "2026 yazı için fırsatlara açığım",
      cta1: "İşlerimi gör",
      cta2: "Bana yaz",
      foot1: "İzmir merkezli · 38.41°K, 27.13°D",
      foot2: "Kaydır",
      year: "CİLT 26 · SAYI I",
    },
    about: {
      eyebrow: "Hakkında",
      h: "Çoğunlukla görünmeyen işler, bilerek.",
      p1: "İYTE'de üçüncü sınıf Bilgisayar Mühendisliği öğrencisiyim ve Türkiye'nin işletme devir pazaryeri Devredin'de CTO'yum. Yaptığım şeylerin çoğu görünmez — Postgres replikasyonu, Cloudflare workers, üretimde çalışan AI araçları. İyi olanlar genelde sunucunun arkasında.",
      p2: "İş dışında veritabanı makaleleri okuyorum, yüzlerce mühendislik öğrencisi için Gizli Noel Baba düzenliyorum ve kodla hiç ilgisi olmayan rotalar planlıyorum.",
      facts: [
        { label: "İzmir merkezli", icon: "pin" },
        { label: "Şu an: DDIA, Bölüm 3", icon: "book" },
        { label: "Kafe > yurt odası", icon: "cup" },
        { label: "Diller: TR · EN", icon: "globe" },
      ],
      caption: ["Şek. 01 — portre, nisan '26", "İzmir · 35mm"],
    },
    exp: {
      eyebrow: "Tecrübe",
      h: "Aslında ne inşa ediyorum.",
      items: [
        {
          period: "2024 — Bugün",
          role: "Teknolojiden Sorumlu Yönetici",
          where: "Devredin · İzmir",
          tags: ["altyapı", "yapay zeka", "veri"],
          bullets: [
            "Türkiye'nin işletme devir pazaryerinde tüm mühendisliği yönetiyorum. %2.5 hisse.",
            "Üretimi eski Nginx/Apache kurulumundan sertleştirilmiş Debian + Nginx yığınına taşıdım.",
            "mcp.devredin.com'u kurdum — platform verisini iç araçlara açan bir MCP sunucusu.",
            "1.261+ aktif ilan üzerine kurulu haftalık iş raporu üreticisi ve değerleme modülünü tasarladım.",
            "CDN'i BunnyCDN'den Cloudflare'e (görsel dönüşümleriyle birlikte) geçirdim.",
            "Ticaret Bakanlığı ile EİDS Faz-2 ticari gayrimenkul entegrasyonunun sahibiyim.",
          ],
        },
        {
          period: "2025 — Bugün",
          role: "Kurucu Ortak · Mühendis",
          where: "benzersor.com · gizli mod",
          tags: ["gizli", "kurucu"],
          bullets: [
            "%10 hisseyle kurucu ortak. Sessizce inşa ediliyor. Lansmana kadar detay yok.",
          ],
        },
        {
          period: "2023 — 2024",
          role: "Serbest · Mühendislik",
          where: "Çeşitli · İzmir / Uzaktan",
          tags: ["serbest", "full-stack"],
          bullets: [
            "Erken aşamadaki Türk ekipler için iç araçlar, panolar, zamanlanmış işler.",
            "Cloudflare Workers ve Postgres replikasyonunu sahada öğrendim — müşterilerin yazmadığı post-mortem'leri ben yazdım.",
          ],
        },
      ],
    },
    proj: {
      eyebrow: "Seçilmiş işler",
      h: "Seçilmiş işler",
      meta: "Altı parça · 2023 — bugün · kaydır →",
      items: [
        {
          k: "MCP-01",
          title: "Devredin MCP Sunucusu",
          host: "mcp.devredin.com",
          desc: "Türkiye'deki ilk üretim MCP kurulumlarından biri. Pazaryeri veritabanını analitik ve operasyon için iç AI araçlarına açıyor.",
          stack: ["Node.js", "MCP", "PostgreSQL", "Cloudflare"],
          year: "'26",
        },
        {
          k: "RPT-02",
          title: "Haftalık İş Raporu",
          host: "Devredin · iç araç",
          desc: "Ham pazaryeri verisinden haftalık editöryal kalitede rapor. SQL'e bağlı LLM'ler — uydurma sayı yok.",
          stack: ["Postgres", "LLM API", "Prompt orkestrasyon"],
          year: "'25",
        },
        {
          k: "VAL-03",
          title: "İlan Değerlemesi",
          host: "Devredin · üretim",
          desc: "1.261+ aktif ilan üstüne kurulu ampirik değerleme. Sezgisel fiyatlamayı veriyle değiştirir, güven aralığıyla.",
          stack: ["Postgres", "TypeScript", "İstatistik"],
          year: "'25",
        },
        {
          k: "MAP-04",
          title: "SiksokHarita",
          host: "İYTE · CENG 318 HCI",
          desc: "Anlık kampüs ring takibi. Canlı konum, ETA tahmini, rota geçmişi. HCI dersi bitirme projesi.",
          stack: ["React", "Spring Boot", "PostgreSQL"],
          year: "'24",
        },
        {
          k: "SAN-05",
          title: "iyteyilbasi Gizli Noel Baba",
          host: "Topluluk · İYTE",
          desc: "Eşleştirme platformunu kurdum. Yılbaşında 200+ mühendislik öğrencisini eşleştirdim — iki kez. Sıcak, festival havasında, bilerek farklı.",
          stack: ["Next.js", "Postgres", "Resend"],
          year: "'24",
        },
        {
          k: "BNZ-06",
          title: "benzersor.com",
          host: "gizli · 2026",
          desc: "Kurucu ortak. Burada gördüğünüz placeholder kart, paylaşmama izin verilen şeyden fazlası. Yakında konuşuruz.",
          stack: ["gizli"],
          year: "'26",
        },
      ],
    },
    stack: {
      eyebrow: "Teknoloji",
      h: "Mutfak nasıl çalışıyor.",
      categories: [
        { id: "lang", title: "Diller", items: [
          { name: "TypeScript", note: "Varsayılan. Çoğu şey buradan başlar." },
          { name: "Java", note: "Spring Boot işleri; çoğunlukla İYTE arka mutfağı." },
          { name: "Python", note: "Scriptler, scraperlar, prompt orkestrasyonu." },
          { name: "SQL", note: "Postgres lehçesi. Bildiğim en faydalı dil." },
        ]},
        { id: "front", title: "Önyüz", items: [
          { name: "React", note: "Rahatım. Sıkıcı. Tahmin edilebilir. İyi." },
          { name: "Next.js", note: "App Router. RSC pragmatik olarak, dini olarak değil." },
          { name: "Tailwind", note: "Saflarla aynı fikirde değilim, yine de hızlı." },
        ]},
        { id: "back", title: "Arka uç", items: [
          { name: "Node.js", note: "Devredin API yüzeyinin çoğu burada." },
          { name: "Spring Boot", note: "Ders işi ve bir freelance proje." },
          { name: "Prisma", note: "Şema gerçektir. Migration'larıma güveniyorum." },
        ]},
        { id: "data", title: "Veri", items: [
          { name: "PostgreSQL", note: "Replikasyon şu an CENG 465 için çalıştığım konu." },
          { name: "Redis", note: "Cache + kuyruklar. Sihir değil. Faydalı." },
        ]},
        { id: "infra", title: "Altyapı", items: [
          { name: "Debian", note: "Devredin'i eski yığından buraya taşıdım." },
          { name: "Nginx", note: "Hâlâ tercih ettiğim ters proxy." },
          { name: "Cloudflare", note: "CDN, Workers, Email Routing. Tamamı." },
          { name: "AWS Lightsail", note: "Ucuz, öngörülebilir, yoldan çekilir." },
        ]},
        { id: "ai", title: "AI / Araçlar", items: [
          { name: "MCP", note: "mcp.devredin.com'u kurdum. Erken benimseyici, fanatik değil." },
          { name: "LLM APIs", note: "Anthropic, OpenAI. Sadece bağlı çıktı." },
          { name: "CodeRabbit", note: "PR'larda beni benden kurtarıyor." },
        ]},
      ],
    },
    edu: {
      eyebrow: "Eğitim",
      h: "Diplomalar nereden geliyor.",
      school: "İzmir Yüksek Teknoloji Enstitüsü",
      schoolEm: "İYTE",
      degree: "Bilgisayar Mühendisliği — üçüncü sınıf",
      gpa: [
        { label: "GANO", value: "3.93 / 4.00" },
        { label: "YKS Sıralama", value: "İlk 2.6k / 3M" },
        { label: "Mezuniyet", value: "2027" },
      ],
      courses: [
        { code: "CENG 465", name: "Veri-yoğun Uygulama Tasarımı", term: "Bahar '26" },
        { code: "CENG 318", name: "İnsan-Bilgisayar Etkileşimi", term: "Güz '25" },
        { code: "MATH 313", name: "Kriptografi", term: "Güz '25" },
        { code: "CENG 311", name: "Algoritmalar", term: "Bahar '25" },
        { code: "CENG 222", name: "BÇ İçin İstatistik", term: "Güz '24" },
      ],
      learningLabel: "Şu an öğrendiklerim",
      learning: [
        "Postgres logical replication",
        "pgvector ile vektör arama",
        "Linear sync engine",
        "MCP sunucu desenleri",
        "Cloudflare Durable Objects",
        "Olasılıksal veri yapıları",
        "Postgres logical replication",
      ],
    },
    playground: {
      eyebrow: "Atölye",
      h: "Küçük bir atölye. Mod değiştir.",
      lede: "Editöryal site sönümleniyor ve sayfa bir alete dönüşüyor. Her modül önce kendim için yaptığım bir şey; siz de oynayabilirsiniz.",
      pulse: { title: "Canlı Devredin nabzı", desc: "MCP sunucusundan filtrelenmiş anlık görüntü. Saatlik yenileniyor. Pano değil — kalp atışı.", foot: "Demo için sahte veri · son senk. 14d önce" },
      val: { title: "İlan değerleme oyuncağı", desc: "Bir kategori ve gelir yaz. Tahmin sayı değil bir aralık döndürür. Eğitim amaçlı, teklif değil.", foot: "1.261 aktif ilan üzerine · sadece eğitim" },
      repl: { title: "Postgres replikasyonu, görünür", desc: "Primary commit, WAL aktarımı, replica yetişiyor. Gecikme görebileceğin bir özellik.", foot: "CENG 465'e bağlı · ortalama gecikme 0.4s" },
      term: { title: "Terminal", desc: "Sitenin herhangi bir yerinde ~ tuşuna bas. Birkaç dürüst komut.", foot: "tilde (~) ile aç · esc ile kapat" },
    },
    writing: {
      eyebrow: "Yazılar",
      h: "Notlar, blog değil.",
      empty: "Şu an bilerek boş.",
      emptyDesc: "Burada bayat 'temiz kod' fikirleri yerine hiçbir şey olmasını tercih ederim. İlk yazı söyleyecek bir şeyim olduğunda gelir — büyük ihtimalle Postgres replikasyonu ya da MCP'nin dağınık tarafı hakkında.",
      cta: "Çıkınca haber ver",
    },
    contact: {
      bigTop: "Bilmem gereken",
      bigBottom: "bir şey üstünde mi çalışıyorsun?",
      email: "hi@erdm.io",
      socials: { gh: "github/erdmio", li: "linkedin/erdmio", tw: "x/erdmio" },
      colophon: "© 2026 · İzmir'de yapıldı · Instrument Serif & Inter Tight · Cloudflare üstünde",
      now: "Şu an: Postgres logical decoding",
    },
  },
};
