import type { Content, Lang } from "./lib/types";

export const CONTENT: Record<Lang, Content> = {
  en: {
    nav: [
      { id: "intro", label: "Intro" },
      { id: "about", label: "About" },
      { id: "experience", label: "Experience" },
      { id: "projects", label: "Projects" },
      { id: "stack", label: "Stack" },
      { id: "education", label: "Education" },
      { id: "playground", label: "Playground" },
      { id: "writing", label: "Writing" },
      { id: "contact", label: "Contact" },
    ],
    hero: {
      first: "Erdem",
      last: "Yılmaz",
      role: "Software engineer @ DevirVentures · CS @ İYTE",
      tagline: "I build the quiet systems that run when no one's watching.",
      status: "",
      cta1: "See my work",
      cta2: "Get in touch",
      foot1: "Based in İzmir · 38.320864, 26.640437",
      foot2: "Scroll",
      year: "VOL. 26 · ISSUE I",
    },
    about: {
      eyebrow: "About",
      h: "Mostly invisible work, on purpose.",
      p1: "I'm a third-year Computer Engineering student at İYTE and a software engineer at DevirVentures — the holding behind Devredin, agend.co, and a few other quiet bets. Most of what I do is invisible — NestJS APIs, Postgres replication, Hetzner and AWS servers, Cloudflare edges, Ansible playbooks, backup jobs, and AI tooling that runs in production. The good stuff is usually behind a server.",
      p2: "Outside work, I keep a few side projects alive — including zincirikirma.com, a free habit tracker I built and shipped to production — try to get a little better at the boring fundamentals, organize student events for hundreds of engineering friends, and plan road trips that have nothing to do with code.",
      links: [
        { label: "DevirVentures", href: "https://devirventures.com" },
        { label: "Devredin", href: "https://devredin.com" },
        { label: "Zinciri Kırma", href: "https://zincirikirma.com" },
        { label: "agend.co", href: "https://agend.co" },
      ],
      facts: [
        { label: "Based in İzmir", icon: "pin" },
        { label: "Company: DevirVentures", icon: "book", href: "https://devirventures.com" },
        { label: "Focus: product engineering", icon: "spark" },
        { label: "Speaks: TR · EN", icon: "globe" },
      ],
      caption: ["Fig. 01 — portrait, april '26", "İzmir · 35mm"],
    },
    exp: {
      eyebrow: "Experience",
      h: "What I've actually been building.",
      items: [
        {
          period: "Oct 2025 — Present",
          role: "Software Engineer · Part-time",
          where: "DevirVentures · İzmir",
          href: "https://devredin.com",
          tags: ["nestjs", "react", "postgres", "infra", "ai", "expo"],
          bullets: [
            "Engineer at the holding behind Devredin (Turkey's business-transfer marketplace), agend.co, and a few other early-stage bets.",
            "Own the full stack on Devredin: NestJS API, Turborepo monorepo (web · dashboard · dealer · global · storybook), Expo mobile app, Better Auth, Iyzipay payments, BullMQ workers.",
            "Migrated production from a legacy Nginx/Apache split to a hardened Debian + Nginx + Docker stack, automated with Ansible playbooks.",
            "Set up and operate Hetzner Cloud, AWS EC2, and Amazon RDS infrastructure with periodic backup jobs, restore paths, caching, and cost-aware resource sizing.",
            "Built mcp.devredin.com — an MCP server exposing platform data to internal AI tooling, one of the first production MCP deployments in Turkey.",
            "Designed the AI-powered weekly report generator and listing valuation module, grounded in 1,261+ active listings via SQL — no hallucinated numbers.",
            "Cut over the CDN to Cloudflare with image transformations, replacing BunnyCDN. Use Cloudflare Pages, R2, cache rules, and image optimization where they fit.",
            "Coordinate project scope, team priorities, release planning, and Slack bot workflows for operational reports and internal shortcuts.",
          ],
        },
        {
          period: "2025 — Present",
          role: "Co-founder · Engineer",
          where: "benzersor.com · stealth",
          href: "https://benzersor.com",
          tags: ["stealth", "co-founder", "expo"],
          bullets: [
            "Co-founded benzersor. Expo + Next.js, Docker, EAS. Building quietly — details under wraps until launch.",
          ],
        },
        {
          period: "Jun — Oct 2025",
          role: "DevSecOps Intern",
          where: "Research Ecosystems · Remote",
          href: "https://researchecosystems.com",
          tags: ["ansible", "linux", "ci/cd", "infra"],
          bullets: [
            "Promoted from the Java trainee track. Wrote Ansible playbooks, hardened Linux servers, automated deploys, and tightened the team's release pipeline.",
            "Picked up the operational side of the stack — observability, secrets, rollbacks — that engineers usually skip until production hurts.",
          ],
        },
        {
          period: "Feb — Jun 2025",
          role: "Java Backend Developer Trainee",
          where: "Research Ecosystems · Urla, İzmir",
          href: "https://researchecosystems.com",
          tags: ["java", "spring boot", "postgres", "tests"],
          bullets: [
            "Worked with a mentor on simulated real-world backend systems — Spring Boot APIs end-to-end, separating backend layers properly, writing E2E tests, building simple CI/CD pipelines.",
            "First place I learned what \"backend best practice\" actually meant in production, not just on paper.",
          ],
        },
        {
          period: "Jul — Aug 2024",
          role: "Software Developer Intern",
          where: "AES Group · Bursa",
          href: "https://aesgroup.com.tr",
          tags: ["c#", "wpf", "windows"],
          bullets: [
            "Shipped a WPF/C# tool that generates IO files for CNC machines from Excel-driven configurations. Used on the shop floor.",
          ],
        },
      ],
    },
    proj: {
      eyebrow: "Selected projects",
      h: "Selected works",
      meta: "Eight pieces · 2023 — present · scroll →",
      items: [
        {
          k: "PLT-01",
          title: "Devredin Platform",
          host: "devredin.com · production",
          href: "https://devredin.com",
          desc: "Full marketplace stack I lead end-to-end — NestJS API, Turborepo monorepo across five web apps and a shared design system, Expo mobile, Iyzipay, Better Auth, Cloudflare.",
          stack: ["NestJS", "Turborepo", "Expo", "Postgres", "BullMQ"],
          year: "'24 →",
        },
        {
          k: "ZNK-02",
          title: "Zinciri Kırma",
          host: "zincirikirma.com · production",
          href: "https://zincirikirma.com",
          desc: "Free, ad-free habit tracker built around streaks. Daily and weekly habits, social loops with friends, and a polished mobile-first UI. Bilingual (TR · EN), self-hosted on the same boring stack I trust.",
          stack: ["Next.js", "Prisma", "Postgres", "next-intl"],
          year: "'25 →",
        },
        {
          k: "MCP-03",
          title: "Devredin MCP Server",
          host: "mcp.devredin.com",
          href: "https://mcp.devredin.com",
          desc: "One of the first production MCP deployments in Turkey. Exposes the marketplace database to internal AI tooling for analytics, ops, and grounded LLM answers.",
          stack: ["MCP SDK", "Node.js", "Prisma", "Postgres"],
          year: "'26",
        },
        {
          k: "BUS-04",
          title: "iyteulasim.com",
          host: "personal · İzmir",
          href: "https://iyteulasim.com",
          desc: "Public transit hours, fixed. Built to solve the genuinely awful schedule problem between İYTE campus and the city. Currently down — quietly being rebuilt.",
          stack: ["Next.js", "Postgres", "Cloudflare"],
          year: "'24",
        },
        {
          k: "MAP-05",
          title: "IYTE Ring",
          host: "İYTE · CENG 318 HCI",
          desc: "Real-time campus shuttle tracking. Live positions, ETA estimates, route history, designed against the actual constraints students complained about. HCI capstone.",
          stack: ["React", "Spring Boot", "Postgres"],
          year: "'25",
        },
        {
          k: "SAN-06",
          title: "iyteyilbasi Secret Santa",
          host: "Community · İYTE",
          href: "https://iyteyilbasi.com",
          desc: "Built the matching platform for the 2025-26 New Year exchange. 200 participations across the whole İYTE campus — warm, festive, off-brand on purpose.",
          stack: ["Next.js", "Postgres", "Resend"],
          year: "'25",
        },
        {
          k: "BNZ-07",
          title: "benzersor.com",
          host: "stealth · 2026",
          href: "https://benzersor.com",
          desc: "Co-founded. The placeholder card you're looking at is more than I'm allowed to show. Talk soon.",
          stack: ["redacted"],
          year: "'26",
        },
        {
          k: "CLI-08",
          title: "ports",
          host: "github.com/erdemylmaz/ports-cli · open source",
          href: "https://github.com/erdemylmaz/ports-cli",
          desc: "Project-aware lsof for macOS. Single-file Go CLI that shows which dev project each listening port belongs to, how long it has been running, who spawned it, and lets you kill, pause, or resume by port number.",
          stack: ["Go", "macOS", "CLI", "MIT"],
          year: "'26",
        },
        {
          k: "GH-09",
          title: "And more →",
          host: "github.com/erdemylmaz",
          href: "https://github.com/erdemylmaz",
          desc: "Side experiments, smaller utilities, and the half-finished things that never make it to a portfolio page. Hop over to GitHub for the rest.",
          stack: ["open source", "weekend builds"],
          year: "→",
        },
      ],
    },
    stack: {
      eyebrow: "Tech",
      h: "How the kitchen is run.",
      categories: [
        {
          id: "lang",
          title: "Languages",
          items: [
            { name: "TypeScript", note: "Default. Most things start here." },
            { name: "Java", note: "Spring Boot freelance work and CENG 211 onwards." },
            { name: "Python", note: "Scripts, scrapers, data wrangling, prompt orchestration." },
            { name: "SQL", note: "Postgres dialect. The most useful language I know." },
            { name: "Bash", note: "Servers don't deploy themselves." },
          ],
        },
        {
          id: "front",
          title: "Frontend",
          items: [
            { name: "React", note: "Comfortable. Boring. Predictable. Good." },
            { name: "Next.js", note: "App Router. RSC pragmatically, not religiously." },
            { name: "React Native", note: "Devredin mobile is Expo + Reanimated + Maps." },
            { name: "Tailwind", note: "Disagree with purists. Ship faster anyway." },
            { name: "Storybook", note: "Single source of truth for the design system." },
          ],
        },
        {
          id: "back",
          title: "Backend",
          items: [
            { name: "NestJS", note: "Devredin's API surface. Modules, guards, queues, GraphQL." },
            { name: "Spring Boot", note: "Java services for IYTE Ring and freelance projects." },
            { name: "Node.js", note: "Workers, MCP server, glue code." },
            { name: "Prisma", note: "Schema as truth. Migrations I trust." },
            { name: "GraphQL", note: "@nestjs/graphql for richer dashboard reads." },
            { name: "BullMQ", note: "Cron, retries, dead-letter queues, observability." },
          ],
        },
        {
          id: "data",
          title: "Data",
          items: [
            { name: "PostgreSQL", note: "Replication is what I'm studying for CENG 465 right now." },
            { name: "Amazon RDS", note: "Managed Postgres when backups, patching, and failover should be somebody else's pager." },
            { name: "Redis", note: "Cache + pub/sub + BullMQ backend." },
            { name: "AWS S3", note: "Presigned URLs, lifecycle rules, and boringly durable object storage." },
            { name: "Cloudflare R2", note: "S3-compatible storage when egress costs matter." },
            { name: "Automated backups", note: "Periodic database and file backups with retention, restore checks, and alerts." },
          ],
        },
        {
          id: "infra",
          title: "Infra & Ops",
          items: [
            { name: "Hetzner Cloud", note: "Cost-efficient VPS hosting for production Linux workloads." },
            { name: "AWS EC2", note: "Elastic compute for services that need AWS-native networking or scale knobs." },
            { name: "Amazon RDS", note: "Managed relational databases with snapshots, upgrades, and sane operations." },
            { name: "Debian", note: "Migrated Devredin from a legacy stack to this." },
            { name: "Nginx", note: "Reverse proxy of choice. Still." },
            { name: "Server provisioning", note: "From a clean box to hardened SSH, firewall, users, services, logs, and deploys." },
            { name: "Docker", note: "Multi-stage builds, dev compose, prod images." },
            { name: "Ansible", note: "Provisioning + deploys. The boring kind that doesn't break." },
            { name: "Cloudflare", note: "DNS, CDN, WAF, Cache Rules, Workers, Email Routing, and traffic steering." },
            { name: "Cloudflare Pages", note: "Static and edge-deployed frontends with preview deployments." },
            { name: "Cloudflare Images", note: "Image resizing, format negotiation, and delivery optimization." },
            { name: "Image optimization", note: "AVIF/WebP, responsive variants, lazy loading, and CDN transforms." },
            { name: "Caching strategy", note: "HTTP cache headers, edge cache, Redis cache, and invalidation that does not haunt you." },
            { name: "Cost optimization", note: "Right-sized servers, storage egress choices, cache hit rates, and fewer surprise invoices." },
            { name: "AWS Lightsail", note: "Cheap, predictable, gets out of the way." },
            { name: "Turborepo · pnpm", note: "Monorepo task graph + workspaces. Caching matters." },
          ],
        },
        {
          id: "delivery",
          title: "Delivery & Team",
          items: [
            { name: "Project management", note: "Roadmaps, scopes, release planning, and turning vague ideas into shippable chunks." },
            { name: "Team management", note: "Owning priorities, reviews, coordination, and the small rituals that keep teams moving." },
            { name: "Slack apps", note: "Internal bots for reports, notifications, approvals, and operational shortcuts." },
            { name: "GitHub Actions", note: "CI pipelines, preview builds, checks, and deployment automation." },
            { name: "Release management", note: "Staged rollouts, rollback paths, migration windows, and calm deploy notes." },
            { name: "Runbooks", note: "Documented recovery paths for backups, incidents, queues, and server moves." },
          ],
        },
        {
          id: "seo",
          title: "SEO & Growth",
          items: [
            { name: "Technical SEO", note: "Crawlability, canonical URLs, redirects, metadata, robots.txt, and sitemap hygiene." },
            { name: "Schema.org / JSON-LD", note: "Structured data for products, organizations, breadcrumbs, FAQs, and rich results." },
            { name: "Indexing strategy", note: "Controlling what gets indexed, refreshed, merged, or noindexed before it pollutes search." },
            { name: "Google Search Console", note: "Coverage checks, performance queries, indexing requests, and debugging search visibility." },
            { name: "PageSpeed optimization", note: "Core Web Vitals, image weight, bundle size, caching, and render path fixes." },
            { name: "Rich text SEO", note: "CMS-safe headings, internal links, snippets, slugs, and content structure that survives editors." },
            { name: "Keyword mapping", note: "Search intent, page targeting, long-tail clusters, and practical content briefs." },
            { name: "Programmatic SEO", note: "pSEO templates, parameterized landing pages, unique copy, and index-safe scale." },
          ],
        },
        {
          id: "quality",
          title: "Quality",
          items: [
            { name: "Jest", note: "Unit + integration. Honest test pyramid, not a vanity metric." },
            { name: "E2E tests", note: "Run against a real database, not mocks. We learned the hard way." },
            { name: "CodeRabbit", note: "Saves me from myself in PRs." },
            { name: "Better Auth", note: "Self-hosted, typed, no vendor lock-in." },
          ],
        },
        {
          id: "ai",
          title: "AI / Tooling",
          items: [
            { name: "MCP", note: "Built mcp.devredin.com. Early adopter, not zealot." },
            { name: "Anthropic SDK", note: "Default for grounded outputs." },
            { name: "OpenAI", note: "Used where it's cheaper or faster." },
            { name: "Prompt eval", note: "Outputs grounded in SQL, evaluated weekly." },
          ],
        },
      ],
    },
    edu: {
      eyebrow: "Education",
      h: "Where the credentials come from.",
      school: "İzmir Institute of Technology",
      schoolEm: "İYTE",
      degree: "BSc, Computer Engineering — third year",
      gpa: [
        { label: "GPA", value: "3.93 / 4.00" },
        { label: "YKS Rank", value: "Top 2.6k of 3M" },
        { label: "Class of", value: "2027" },
      ],
      courses: [
        { code: "MATH 141", name: "Calculus I", term: "1st Semester", hours: "(3+2)", credits: "4", ects: "5" },
        { code: "PHYS 121", name: "General Physics I", term: "1st Semester", hours: "(3+2)", credits: "4", ects: "7" },
        { code: "CENG 111", name: "Concepts in Computer Engineering", term: "1st Semester", hours: "(3+0)", credits: "3", ects: "5" },
        { code: "CENG 113", name: "Programming Basics", term: "1st Semester", hours: "(3+2)", credits: "4", ects: "6" },
        { code: "CENG 115", name: "Discrete Structures", term: "1st Semester", hours: "(3+0)", credits: "3", ects: "5" },
        { code: "ENG 101", name: "Development of Reading and Writing Skills I", term: "1st Semester", hours: "(3+0)", credits: "3", ects: "3" },
        { code: "MATH 142", name: "Calculus II", term: "2nd Semester", hours: "(3+2)", credits: "4", ects: "6" },
        { code: "PHYS 122", name: "General Physics II", term: "2nd Semester", hours: "(3+2)", credits: "4", ects: "8" },
        { code: "MATH 144", name: "Finite Mathematics", term: "2nd Semester", hours: "(3+0)", credits: "3", ects: "5" },
        { code: "CENG 112", name: "Data Structures", term: "2nd Semester", hours: "(3+0)", credits: "3", ects: "5", prereq: "CENG 113" },
        { code: "ECON 106", name: "Principles of Economics", term: "2nd Semester", hours: "(3+0)", credits: "3", ects: "3" },
        { code: "ENG 102", name: "Development of Reading and Writing Skills II", term: "2nd Semester", hours: "(3+0)", credits: "3", ects: "3" },
        { code: "GCC 101", name: "Career Planning and Development", term: "2nd Semester", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "CENG 211", name: "Programming Fundamentals", term: "3rd Semester", hours: "(3+0)", credits: "3", ects: "5", prereq: "CENG 113" },
        { code: "CENG 213", name: "Theory of Computation", term: "3rd Semester", hours: "(3+0)", credits: "3", ects: "5" },
        { code: "CENG 215", name: "Circuits and Electronics", term: "3rd Semester", hours: "(3+2)", credits: "4", ects: "6" },
        { code: "MATH 255", name: "Differential Equations", term: "3rd Semester", hours: "(4+0)", credits: "4", ects: "6" },
        { code: "NTE", name: "Non Technical Elective", term: "3rd Semester", hours: "(3+0)", credits: "3", ects: "3" },
        { code: "HIST 201", name: "Principles of Ataturk I", term: "3rd Semester", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "TURK 201", name: "Turkish Language I", term: "3rd Semester", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "HIST 203", name: "History of the Turkish Revolution I (*)", term: "3rd Semester", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "TURK 203", name: "Turkish for Foreigners (*)", term: "3rd Semester", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "CENG 212", name: "Concepts of Programming Languages", term: "4th Semester", hours: "(3+0)", credits: "3", ects: "5" },
        { code: "CENG 214", name: "Logic Design", term: "4th Semester", hours: "(3+2)", credits: "4", ects: "6" },
        { code: "CENG 216", name: "Numerical Computation", term: "4th Semester", hours: "(3+0)", credits: "3", ects: "5" },
        { code: "CENG 218", name: "Analysis and Design of Algorithms", term: "4th Semester", hours: "(3+0)", credits: "3", ects: "5" },
        { code: "CENG 222", name: "Probability and Statistics", term: "4th Semester", hours: "(3+0)", credits: "3", ects: "5" },
        { code: "HIST 202", name: "Principles of Ataturk II", term: "4th Semester", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "TURK 202", name: "Turkish Language II", term: "4th Semester", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "HIST 204", name: "History of the Turkish Revolution II (*)", term: "4th Semester", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "TURK 204", name: "Turkish for Foreigners (*)", term: "4th Semester", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "CENG 311", name: "Computer Architecture", term: "5th Semester", hours: "(3+2)", credits: "4", ects: "8", prereq: "CENG 214" },
        { code: "MAN 217", name: "Fundamentals of Management and Leadership", term: "5th Semester", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 315", name: "Information Management", term: "5th Semester", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 465", name: "Designing Data-Intensive Systems", term: "5th Semester", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "ART 240", name: "Concepts and Theories of Painting Art", term: "5th Semester", hours: "(3+0)", credits: "3", ects: "3" },
        { code: "CENG 312", name: "Computer Networks", term: "6th Semester", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 316", name: "Software Engineering", term: "6th Semester", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 318", name: "Human Computer Interaction", term: "6th Semester", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 322", name: "Operating Systems", term: "6th Semester", hours: "(3+2)", credits: "4", ects: "8" },
        { code: "TE II", name: "Technical Elective II", term: "6th Semester", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 411", name: "Professional Issues in Computer Engineering", term: "7th Semester", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 415", name: "Senior Design Project & Seminar I", term: "7th Semester", hours: "(3+0)", credits: "3", ects: "8" },
        { code: "TE III", name: "Technical Elective III", term: "7th Semester", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "TE IV", name: "Technical Elective IV", term: "7th Semester", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "NTE II", name: "Non Technical Elective II", term: "7th Semester", hours: "(3+0)", credits: "3", ects: "3" },
        { code: "CENG 400", name: "Summer Practice", term: "7th Semester", credits: "0", ects: "4" },
        { code: "RE II", name: "Restricted Elective II", term: "8th Semester", hours: "(3+0)", credits: "3", ects: "6", prereq: "CENG 415" },
        { code: "RE III", name: "Restricted Elective III", term: "8th Semester", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 416", name: "Senior Design Project & Seminar II", term: "8th Semester", hours: "(3+0)", credits: "3", ects: "8", prereq: "CENG 415" },
        { code: "TE V", name: "Technical Elective V", term: "8th Semester", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "TE VI", name: "Technical Elective VI", term: "8th Semester", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 323", name: "Project Management", term: "Restricted Electives" },
        { code: "CENG 418", name: "Information Security", term: "Restricted Electives" },
        { code: "CENG 424", name: "Embedded Computer Systems", term: "Restricted Electives" },
        { code: "CENG 370", name: "Mainframe Computing", term: "Technical Electives · 3rd Year" },
        { code: "CENG 381", name: "Stochastic Processes", term: "Technical Electives · 3rd Year" },
        { code: "CENG 382", name: "Information Theory", term: "Technical Electives · 3rd Year" },
        { code: "CENG 383", name: "Real-Time Systems", term: "Technical Electives · 3rd Year" },
        { code: "CENG 384", name: "Microprocessors", term: "Technical Electives · 3rd Year" },
        { code: "CENG 385", name: "Mathematical Logic", term: "Technical Electives · 3rd Year" },
        { code: "CENG 386", name: "Fuzzy Logic Systems", term: "Technical Electives · 3rd Year" },
        { code: "CENG 388", name: "Web Programming", term: "Technical Electives · 3rd Year" },
        { code: "CENG 389", name: "Mobile Application Development", term: "Technical Electives · 3rd Year" },
        { code: "CENG 390", name: "Cloud Computing", term: "Technical Electives · 3rd Year" },
        { code: "CENG 391", name: "Introduction to Image Understanding", term: "Technical Electives · 3rd Year" },
        { code: "CENG 421", name: "Network Programming", term: "Technical Electives · 4th Year" },
        { code: "CENG 422", name: "Network Design & Management", term: "Technical Electives · 4th Year" },
        { code: "CENG 431", name: "Building Software Systems", term: "Technical Electives · 4th Year" },
        { code: "CENG 432", name: "Fundamentals of Enterprise Application Development", term: "Technical Electives · 4th Year" },
        { code: "CENG 433", name: "Scalable Software Development for Internet", term: "Technical Electives · 4th Year" },
        { code: "CENG 434", name: "Enterprise Application Integration", term: "Technical Electives · 4th Year" },
        { code: "CENG 435", name: "Database System Design and Implementation", term: "Technical Electives · 4th Year", prereq: "CENG 315" },
        { code: "CENG 436", name: "Distributed Information Management", term: "Technical Electives · 4th Year", prereq: "CENG 315" },
        { code: "CENG 437", name: "Software Quality Management", term: "Technical Electives · 4th Year", prereq: "CENG 316" },
        { code: "CENG 441", name: "Introduction to Parallel Programming", term: "Technical Electives · 4th Year" },
        { code: "CENG 442", name: "Multicore Architectures and Operating Systems", term: "Technical Electives · 4th Year" },
        { code: "CENG 443", name: "Heterogeneous Parallel Programming", term: "Technical Electives · 4th Year" },
        { code: "CENG 444", name: "Parallel Programming Patterns", term: "Technical Electives · 4th Year" },
        { code: "CENG 451", name: "Advanced Digital System Design", term: "Technical Electives · 4th Year" },
        { code: "CENG 452", name: "Building Software for Embedded Systems", term: "Technical Electives · 4th Year" },
        { code: "CENG 461", name: "Artificial Intelligence", term: "Technical Electives · 4th Year" },
        { code: "CENG 462", name: "Soft Computing", term: "Technical Electives · 4th Year" },
        { code: "CENG 463", name: "Introduction to Machine Learning", term: "Technical Electives · 4th Year" },
        { code: "CENG 464", name: "Text Mining", term: "Technical Electives · 4th Year" },
        { code: "CENG 465", name: "Principles of Data-Intensive Systems", term: "Technical Electives · 4th Year" },
        { code: "CENG 467", name: "Natural Language Understanding and Generation", term: "Technical Electives · 4th Year" },
        { code: "CENG 471", name: "Cryptography", term: "Technical Electives · 4th Year" },
        { code: "CENG 472", name: "Network Security", term: "Technical Electives · 4th Year" },
        { code: "CENG 473", name: "Security of Information and Communication Technologies", term: "Technical Electives · 4th Year" },
        { code: "CENG 481", name: "Theoretical Approaches in Computer Science", term: "Technical Electives · 4th Year" },
        { code: "CENG 482", name: "Evolutionary Computation", term: "Technical Electives · 4th Year" },
        { code: "CENG 483", name: "Behavioural Robotics", term: "Technical Electives · 4th Year" },
        { code: "CENG 484", name: "Data Mining", term: "Technical Electives · 4th Year" },
        { code: "CENG 485", name: "Information Technology Entrepreneurship", term: "Technical Electives · 4th Year" },
        { code: "CENG 486", name: "Entrepreneurship for Smart Business", term: "Technical Electives · 4th Year" },
        { code: "CENG 487", name: "Introduction to Computer Graphics", term: "Technical Electives · 4th Year" },
        { code: "CENG 488", name: "Computer Graphics", term: "Technical Electives · 4th Year" },
        { code: "CENG 491", name: "Field Course", term: "Technical Electives · 4th Year" },
        { code: "CENG 499", name: "Cooperative Education (COOP)", term: "Technical Electives · 4th Year" },
      ],
      learningLabel: "Currently learning",
      learning: [
        "Postgres logical replication",
        "Vector search with pgvector",
        "Linear's sync engine",
        "MCP server design patterns",
        "Cloudflare Durable Objects",
        "Probabilistic data structures",
        "Postgres logical replication",
      ],
    },
    playground: {
      eyebrow: "Playground",
      h: "A small workshop. Switch modes.",
      lede: "The editorial site dims and the page becomes a tool. Each module is a thing I made for myself first; you're welcome to poke them.",
      ports: {
        title: "ports — project-aware lsof",
        desc: "A small Go CLI I built for macOS. Shows which dev project each listening port belongs to, how long it has been running, and lets you kill, pause, or resume by port number. Try the sort modes.",
        foot: "Single-file Go · MIT · v0.3.0 ·",
      },
      sql: {
        title: "Portfolio SQL",
        desc: "A tiny read-only database of this site. Try \\d, \\d projects, or SELECT queries against the sections.",
        foot: "read-only parser · try: select * from projects",
      },
      repl: {
        title: "Postgres replication, visible",
        desc: "Primary commits, the WAL ships, the replica catches up. Lag is a feature you can see.",
        foot: "Tied to CENG 465 · idle lag avg 0.4s",
      },
      term: {
        title: "Terminal",
        desc: "Press ~ anywhere on the site to open. A few honest commands.",
        foot: "press tilde (~) to summon · esc to close",
      },
    },
    writing: {
      eyebrow: "Writing",
      h: "Notes, not a blog.",
      empty: "Currently empty by choice.",
      emptyDesc:
        "I'd rather have nothing here than have stale opinions about clean code. The first piece will land when I have something worth saying — probably about why flexible code matters more than clever code, why testing pays its rent in production, Postgres replication, and the messier side of MCP.",
      cta: "Notify me",
    },
    contact: {
      bigTop: "Working on something",
      bigBottom: "I should know about?",
      email: "hi@erdm.io",
      socials: { gh: "github/erdemylmaz", li: "linkedin/erdem-yılmaz", ig: "instagram/erdemyilmaz.x" },
      socialsHref: {
        gh: "https://github.com/erdemylmaz",
        li: "https://www.linkedin.com/in/erdem-y%C4%B1lmaz-b497921a8/",
        ig: "https://www.instagram.com/erdemyilmaz.x/",
      },
      colophon: "Made between İzmir, campus, and the occasional long road.",
      now: "Software @ Devredin · co-founder @ benzersor · CS @ İYTE",
    },
  },
  tr: {
    nav: [
      { id: "intro", label: "Giriş" },
      { id: "about", label: "Hakkında" },
      { id: "experience", label: "Tecrübe" },
      { id: "projects", label: "Projeler" },
      { id: "stack", label: "Yığın" },
      { id: "education", label: "Eğitim" },
      { id: "playground", label: "Atölye" },
      { id: "writing", label: "Yazılar" },
      { id: "contact", label: "İletişim" },
    ],
    hero: {
      first: "Erdem",
      last: "Yılmaz",
      role: "Yazılım mühendisi @ DevirVentures · İYTE'de CS",
      tagline: "Kimsenin bakmadığı zamanlarda çalışan sessiz sistemleri kuruyorum.",
      status: "",
      cta1: "İşlerimi gör",
      cta2: "Bana yaz",
      foot1: "İzmir merkezli · 38.320864, 26.640437",
      foot2: "Kaydır",
      year: "CİLT 26 · SAYI I",
    },
    about: {
      eyebrow: "Hakkında",
      h: "Çoğunlukla görünmeyen işler, bilerek.",
      p1: "İYTE'de üçüncü sınıf Bilgisayar Mühendisliği öğrencisiyim ve DevirVentures'ta yazılım mühendisiyim — Devredin, agend.co ve birkaç sessiz girişimin arkasındaki holding. Yaptığım şeylerin çoğu görünmez — NestJS API'ları, Postgres replikasyonu, Hetzner ve AWS sunucuları, Cloudflare edge'i, Ansible playbook'ları, backup işleri ve üretimde çalışan AI araçları. İyi olanlar genelde sunucunun arkasında.",
      p2: "İş dışında birkaç yan projeyi hayatta tutuyorum — ücretsiz alışkanlık takip uygulamam zincirikirma.com da bunlardan biri, üretime çıkmış durumda — sıkıcı ama önemli temellerde biraz daha iyi olmaya çalışıyorum, yüzlerce mühendis arkadaş için öğrenci etkinlikleri düzenliyorum ve kodla hiç ilgisi olmayan rotalar planlıyorum.",
      links: [
        { label: "DevirVentures", href: "https://devirventures.com" },
        { label: "Devredin", href: "https://devredin.com" },
        { label: "Zinciri Kırma", href: "https://zincirikirma.com" },
        { label: "agend.co", href: "https://agend.co" },
      ],
      facts: [
        { label: "İzmir merkezli", icon: "pin" },
        { label: "Şirket: DevirVentures", icon: "book", href: "https://devirventures.com" },
        { label: "Odak: ürün mühendisliği", icon: "spark" },
        { label: "Diller: TR · EN", icon: "globe" },
      ],
      caption: ["Şek. 01 — portre, nisan '26", "İzmir · 35mm"],
    },
    exp: {
      eyebrow: "Tecrübe",
      h: "Aslında ne inşa ediyorum.",
      items: [
        {
          period: "Eki 2025 — Bugün",
          role: "Yazılım Mühendisi · Yarı zamanlı",
          where: "DevirVentures · İzmir",
          href: "https://devredin.com",
          tags: ["nestjs", "react", "postgres", "altyapı", "ai", "expo"],
          bullets: [
            "Devredin (Türkiye'nin işletme devir pazaryeri), agend.co ve birkaç erken aşama girişimin arkasındaki holdingin mühendisi.",
            "Devredin'in tüm yığını benim sorumluluğumda: NestJS API, Turborepo monorepo (web · dashboard · bayi · global · storybook), Expo mobil uygulama, Better Auth, Iyzipay, BullMQ.",
            "Üretimi eski Nginx/Apache kurulumundan sertleştirilmiş Debian + Nginx + Docker yığınına taşıdım, Ansible playbook'ları ile otomatize ettim.",
            "Hetzner Cloud, AWS EC2 ve Amazon RDS altyapısını periyodik backup işleri, restore yolları, caching ve maliyet odaklı kaynak boyutlandırmayla kurup işletiyorum.",
            "mcp.devredin.com'u kurdum — platform verisini iç araçlara açan bir MCP sunucusu, Türkiye'deki ilk üretim MCP kurulumlarından biri.",
            "1.261+ aktif ilan üzerine kurulu haftalık iş raporu üreticisi ve değerleme modülünü tasarladım. SQL'e bağlı çıktı — uydurma sayı yok.",
            "CDN'i BunnyCDN'den Cloudflare'e (görsel dönüşümleriyle birlikte) geçirdim. Uygun yerlerde Cloudflare Pages, R2, cache rule'ları ve görsel optimizasyonu kullanıyorum.",
            "Proje kapsamı, ekip öncelikleri, release planlama ve operasyon raporları/iç kısayollar için Slack bot akışlarını koordine ediyorum.",
          ],
        },
        {
          period: "2025 — Bugün",
          role: "Kurucu Ortak · Mühendis",
          where: "benzersor.com · gizli mod",
          href: "https://benzersor.com",
          tags: ["gizli", "kurucu", "expo"],
          bullets: [
            "benzersor kurucu ortak. Expo + Next.js, Docker, EAS. Sessizce inşa ediliyor — lansmana kadar detay yok.",
          ],
        },
        {
          period: "Haz — Eki 2025",
          role: "DevSecOps Stajyeri",
          where: "Research Ecosystems · Uzaktan",
          href: "https://researchecosystems.com",
          tags: ["ansible", "linux", "ci/cd", "altyapı"],
          bullets: [
            "Java trainee programından terfi. Ansible playbook'ları yazdım, Linux sunucuları sıkılaştırdım, deploy süreçlerini otomatize ettim ve release pipeline'ını disipline ettim.",
            "Yığının operasyonel tarafını — gözlemlenebilirlik, secret yönetimi, rollback'ler — üretim canınız yanmadan öğrendim.",
          ],
        },
        {
          period: "Şub — Haz 2025",
          role: "Java Backend Developer Trainee",
          where: "Research Ecosystems · Urla, İzmir",
          href: "https://researchecosystems.com",
          tags: ["java", "spring boot", "postgres", "test"],
          bullets: [
            "Bir mentörle simüle edilmiş gerçek dünya backend sistemleri üzerinde çalıştım — uçtan uca Spring Boot API'ları, doğru katman ayrımı, E2E testler, basit CI/CD pipeline'ları.",
            "Backend best practice'lerinin kağıt üzerinde değil, üretimde ne anlama geldiğini ilk burada öğrendim.",
          ],
        },
        {
          period: "Tem — Ağu 2024",
          role: "Yazılım Geliştirici Stajyeri",
          where: "AES Group · Bursa",
          href: "https://aesgroup.com.tr",
          tags: ["c#", "wpf", "windows"],
          bullets: [
            "Excel'den okuyan WPF/C# bir araçla CNC tezgâhları için IO dosyaları üreten bir araç geliştirdim. Atölyede kullanıldı.",
          ],
        },
      ],
    },
    proj: {
      eyebrow: "Seçilmiş işler",
      h: "Seçilmiş işler",
      meta: "Sekiz parça · 2023 — bugün · kaydır →",
      items: [
        {
          k: "PLT-01",
          title: "Devredin Platformu",
          host: "devredin.com · üretim",
          href: "https://devredin.com",
          desc: "Uçtan uca yönettiğim tüm pazaryeri yığını — NestJS API, beş web uygulaması ve ortak design system'i barındıran Turborepo monorepo, Expo mobil, Iyzipay, Better Auth, Cloudflare.",
          stack: ["NestJS", "Turborepo", "Expo", "Postgres", "BullMQ"],
          year: "'24 →",
        },
        {
          k: "ZNK-02",
          title: "Zinciri Kırma",
          host: "zincirikirma.com · üretim",
          href: "https://zincirikirma.com",
          desc: "Ücretsiz, reklamsız bir alışkanlık takip uygulaması — seri (streak) odaklı. Günlük ve haftalık alışkanlıklar, arkadaşlarla sosyal döngü, mobil-öncelikli arayüz. İki dilli (TR · EN), güvendiğim sıkıcı yığın üzerinde self-host.",
          stack: ["Next.js", "Prisma", "Postgres", "next-intl"],
          year: "'25 →",
        },
        {
          k: "MCP-03",
          title: "Devredin MCP Sunucusu",
          host: "mcp.devredin.com",
          href: "https://mcp.devredin.com",
          desc: "Türkiye'deki ilk üretim MCP kurulumlarından biri. Pazaryeri veritabanını analitik, operasyon ve LLM çıktıları için iç AI araçlarına açıyor.",
          stack: ["MCP SDK", "Node.js", "Prisma", "Postgres"],
          year: "'26",
        },
        {
          k: "BUS-04",
          title: "iyteulasim.com",
          host: "kişisel · İzmir",
          href: "https://iyteulasim.com",
          desc: "Toplu taşıma saatleri, çözüldü. İYTE kampüsü ile şehir arasındaki gerçekten berbat program sorununa cevap olarak yapıldı. Şu an kapalı — sessizce yeniden yazılıyor.",
          stack: ["Next.js", "Postgres", "Cloudflare"],
          year: "'24",
        },
        {
          k: "MAP-05",
          title: "IYTE Ring",
          host: "İYTE · CENG 318 HCI",
          desc: "Anlık kampüs ring takibi. Canlı konum, ETA tahmini, rota geçmişi — öğrencilerin gerçekten şikayet ettiği kısıtlara göre tasarlandı. HCI bitirme projesi.",
          stack: ["React", "Spring Boot", "Postgres"],
          year: "'25",
        },
        {
          k: "SAN-06",
          title: "iyteyilbasi Gizli Noel Baba",
          host: "Topluluk · İYTE",
          href: "https://iyteyilbasi.com",
          desc: "2025-26 yılbaşı değişimi için eşleştirme platformunu kurdum. Tüm İYTE kampüsünden 200 katılım — sıcak, festival havasında, bilerek farklı.",
          stack: ["Next.js", "Postgres", "Resend"],
          year: "'25",
        },
        {
          k: "BNZ-07",
          title: "benzersor.com",
          host: "gizli · 2026",
          href: "https://benzersor.com",
          desc: "Kurucu ortak. Burada gördüğünüz placeholder kart, paylaşmama izin verilen şeyden fazlası. Yakında konuşuruz.",
          stack: ["gizli"],
          year: "'26",
        },
        {
          k: "CLI-08",
          title: "ports",
          host: "github.com/erdemylmaz/ports-cli · açık kaynak",
          href: "https://github.com/erdemylmaz/ports-cli",
          desc: "macOS için proje farkındalıklı lsof. Tek dosyalık Go CLI; hangi dev projenin hangi portu dinlediğini, ne kadar süredir çalıştığını, kimin başlattığını gösterir; port numarasıyla kill, pause, resume yapmanı sağlar.",
          stack: ["Go", "macOS", "CLI", "MIT"],
          year: "'26",
        },
        {
          k: "GH-09",
          title: "Daha fazlası →",
          host: "github.com/erdemylmaz",
          href: "https://github.com/erdemylmaz",
          desc: "Yan denemeler, küçük araçlar ve portfolyoya hiç çıkmayan yarım kalmış şeyler. Geri kalanı için GitHub'a uğra.",
          stack: ["açık kaynak", "hafta sonu işleri"],
          year: "→",
        },
      ],
    },
    stack: {
      eyebrow: "Teknoloji",
      h: "Mutfak nasıl çalışıyor.",
      categories: [
        {
          id: "lang",
          title: "Diller",
          items: [
            { name: "TypeScript", note: "Varsayılan. Çoğu şey buradan başlar." },
            { name: "Java", note: "Spring Boot freelance işleri ve CENG 211'den itibaren." },
            { name: "Python", note: "Scriptler, scraperlar, veri işleme, prompt orkestrasyonu." },
            { name: "SQL", note: "Postgres lehçesi. Bildiğim en faydalı dil." },
            { name: "Bash", note: "Sunucular kendi kendine deploy olmuyor." },
          ],
        },
        {
          id: "front",
          title: "Önyüz",
          items: [
            { name: "React", note: "Rahatım. Sıkıcı. Tahmin edilebilir. İyi." },
            { name: "Next.js", note: "App Router. RSC pragmatik olarak, dini olarak değil." },
            { name: "React Native", note: "Devredin mobil: Expo + Reanimated + Maps." },
            { name: "Tailwind", note: "Saflarla aynı fikirde değilim, yine de hızlı." },
            { name: "Storybook", note: "Design system'in tek doğru kaynağı." },
          ],
        },
        {
          id: "back",
          title: "Arka uç",
          items: [
            { name: "NestJS", note: "Devredin'in API yüzeyi. Modüller, guard'lar, kuyruklar, GraphQL." },
            { name: "Spring Boot", note: "IYTE Ring ve freelance projelerde Java servisleri." },
            { name: "Node.js", note: "Worker'lar, MCP sunucusu, yapıştırıcı kod." },
            { name: "Prisma", note: "Şema gerçektir. Migration'larıma güveniyorum." },
            { name: "GraphQL", note: "Daha zengin dashboard okumaları için @nestjs/graphql." },
            { name: "BullMQ", note: "Cron, retry, dead-letter, gözlemlenebilirlik." },
          ],
        },
        {
          id: "data",
          title: "Veri",
          items: [
            { name: "PostgreSQL", note: "Replikasyon şu an CENG 465 için çalıştığım konu." },
            { name: "Amazon RDS", note: "Backup, patch ve failover nöbetini yönetilen Postgres'e bırakmak gerektiğinde." },
            { name: "Redis", note: "Cache + pub/sub + BullMQ arka ucu." },
            { name: "AWS S3", note: "Presigned URL, lifecycle rule ve sıkıcı derecede dayanıklı obje depolama." },
            { name: "Cloudflare R2", note: "Egress maliyeti önemli olduğunda S3 uyumlu depolama." },
            { name: "Otomatik backup", note: "Periyodik veritabanı ve dosya yedekleri; retention, restore kontrolü ve uyarılarla." },
          ],
        },
        {
          id: "infra",
          title: "Altyapı",
          items: [
            { name: "Hetzner Cloud", note: "Production Linux workload'ları için maliyet-verimli VPS hosting." },
            { name: "AWS EC2", note: "AWS-native network veya ölçek ayarı gereken servisler için elastic compute." },
            { name: "Amazon RDS", note: "Snapshot, upgrade ve daha sakin operasyonlar için yönetilen ilişkisel veritabanı." },
            { name: "Debian", note: "Devredin'i eski yığından buraya taşıdım." },
            { name: "Nginx", note: "Hâlâ tercih ettiğim ters proxy." },
            { name: "Sunucu kurulumu", note: "Temiz makineden hardened SSH, firewall, kullanıcılar, servisler, loglar ve deploy'a." },
            { name: "Docker", note: "Çok aşamalı build, dev compose, prod imajları." },
            { name: "Ansible", note: "Provisioning + deploy. Patlamayan, sıkıcı türden." },
            { name: "Cloudflare", note: "DNS, CDN, WAF, Cache Rules, Workers, Email Routing ve trafik yönlendirme." },
            { name: "Cloudflare Pages", note: "Preview deployment'lı statik ve edge-deployed frontend'ler." },
            { name: "Cloudflare Images", note: "Görsel resize, format seçimi ve teslim optimizasyonu." },
            { name: "Görsel optimizasyonu", note: "AVIF/WebP, responsive varyantlar, lazy loading ve CDN transform'ları." },
            { name: "Caching stratejisi", note: "HTTP cache header'ları, edge cache, Redis cache ve sonradan üzmeyen invalidation." },
            { name: "Maliyet optimizasyonu", note: "Doğru boyutlu sunucular, storage egress kararları, cache hit rate ve az sürpriz fatura." },
            { name: "AWS Lightsail", note: "Ucuz, öngörülebilir, yoldan çekilir." },
            { name: "Turborepo · pnpm", note: "Monorepo task grafı + workspace. Caching önemli." },
          ],
        },
        {
          id: "delivery",
          title: "Teslim & Ekip",
          items: [
            { name: "Proje yönetimi", note: "Roadmap, kapsam, release planı ve belirsiz fikirleri yayınlanabilir parçalara bölmek." },
            { name: "Ekip yönetimi", note: "Öncelikler, review'lar, koordinasyon ve ekibi akıtan küçük ritüeller." },
            { name: "Slack apps", note: "Rapor, bildirim, onay ve operasyon kısayolları için iç botlar." },
            { name: "GitHub Actions", note: "CI pipeline'ları, preview build'ler, kontroller ve deploy otomasyonu." },
            { name: "Release yönetimi", note: "Kademeli rollout, rollback yolu, migration pencereleri ve sakin deploy notları." },
            { name: "Runbook", note: "Backup, incident, kuyruk ve sunucu taşıma için yazılı toparlanma yolları." },
          ],
        },
        {
          id: "seo",
          title: "SEO & Büyüme",
          items: [
            { name: "Teknik SEO", note: "Crawl edilebilirlik, canonical URL'ler, redirect'ler, metadata, robots.txt ve sitemap düzeni." },
            { name: "Schema.org / JSON-LD", note: "Ürün, organizasyon, breadcrumb, FAQ ve rich result için structured data." },
            { name: "Indexing stratejisi", note: "Neyin indexleneceğini, yenileneceğini, birleştirileceğini veya noindex kalacağını kontrol etmek." },
            { name: "Google Search Console", note: "Coverage, performans sorguları, index istekleri ve arama görünürlüğü debug'ı." },
            { name: "PageSpeed optimizasyonu", note: "Core Web Vitals, görsel ağırlığı, bundle boyutu, caching ve render path düzeltmeleri." },
            { name: "Rich text SEO", note: "CMS'e dayanıklı heading, internal link, snippet, slug ve içerik yapısı." },
            { name: "Keyword mapping", note: "Arama niyeti, sayfa hedefleme, long-tail kümeler ve uygulanabilir içerik brief'leri." },
            { name: "Programmatic SEO", note: "pSEO template'leri, parametrik landing page'ler, özgün içerik ve index-safe ölçek." },
          ],
        },
        {
          id: "quality",
          title: "Kalite",
          items: [
            { name: "Jest", note: "Unit + integration. Süslü metrik değil, dürüst test piramidi." },
            { name: "E2E test", note: "Mock değil, gerçek veritabanına karşı koşar. Zor yoldan öğrendik." },
            { name: "CodeRabbit", note: "PR'larda beni benden kurtarıyor." },
            { name: "Better Auth", note: "Self-hosted, tipli, vendor lock-in yok." },
          ],
        },
        {
          id: "ai",
          title: "AI / Araçlar",
          items: [
            { name: "MCP", note: "mcp.devredin.com'u kurdum. Erken benimseyici, fanatik değil." },
            { name: "Anthropic SDK", note: "Bağlı çıktılar için varsayılan." },
            { name: "OpenAI", note: "Daha ucuz veya hızlı olduğu yerlerde." },
            { name: "Prompt eval", note: "SQL'e bağlı çıktılar, haftalık değerlendirme." },
          ],
        },
      ],
    },
    edu: {
      eyebrow: "Eğitim",
      h: "Diplomalar nereden geliyor.",
      school: "İzmir Yüksek Teknoloji Enstitüsü",
      schoolEm: "İYTE",
      degree: "Bilgisayar Mühendisliği — üçüncü sınıf",
      gpa: [
        { label: "GANO", value: "3.93 / 4.00" },
        { label: "YKS Sıralama", value: "İlk 2.6k / 3M" },
        { label: "Mezuniyet", value: "2027" },
      ],
      courses: [
        { code: "MATH 141", name: "Temel Analiz I", term: "1. Dönem", hours: "(3+2)", credits: "4", ects: "5" },
        { code: "PHYS 121", name: "Genel Fizik I", term: "1. Dönem", hours: "(3+2)", credits: "4", ects: "7" },
        { code: "CENG 111", name: "Bilgisayar Mühendisliği Kavramları", term: "1. Dönem", hours: "(3+0)", credits: "3", ects: "5" },
        { code: "CENG 113", name: "Programlamaya Giriş", term: "1. Dönem", hours: "(3+2)", credits: "4", ects: "6" },
        { code: "CENG 115", name: "Ayrık Yapılar", term: "1. Dönem", hours: "(3+0)", credits: "3", ects: "5" },
        { code: "ENG 101", name: "İngilizce Okuma ve Yazma Becerileri I", term: "1. Dönem", hours: "(3+0)", credits: "3", ects: "3" },
        { code: "MATH 142", name: "Temel Analiz II", term: "2. Dönem", hours: "(3+2)", credits: "4", ects: "6" },
        { code: "PHYS 122", name: "Genel Fizik II", term: "2. Dönem", hours: "(3+2)", credits: "4", ects: "8" },
        { code: "MATH 144", name: "Sonlu Matematik", term: "2. Dönem", hours: "(3+0)", credits: "3", ects: "5" },
        { code: "CENG 112", name: "Veri Yapıları", term: "2. Dönem", hours: "(3+0)", credits: "3", ects: "5", prereq: "CENG 113" },
        { code: "ECON 106", name: "Ekonominin Prensipleri", term: "2. Dönem", hours: "(3+0)", credits: "3", ects: "3" },
        { code: "ENG 102", name: "İngilizce Okuma ve Yazma Becerileri II", term: "2. Dönem", hours: "(3+0)", credits: "3", ects: "3" },
        { code: "GCC 101", name: "Kariyer Planlama ve Geliştirme", term: "2. Dönem", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "CENG 211", name: "Programlamanın Temelleri", term: "3. Dönem", hours: "(3+0)", credits: "3", ects: "5", prereq: "CENG 113" },
        { code: "CENG 213", name: "İşlem Teorisi", term: "3. Dönem", hours: "(3+0)", credits: "3", ects: "5" },
        { code: "CENG 215", name: "Devreler ve Elektronik", term: "3. Dönem", hours: "(3+2)", credits: "4", ects: "6" },
        { code: "MATH 255", name: "Diferansiyel Denklemler", term: "3. Dönem", hours: "(4+0)", credits: "4", ects: "6" },
        { code: "TOS", name: "Teknik Olmayan Seçmeli", term: "3. Dönem", hours: "(3+0)", credits: "3", ects: "3" },
        { code: "HIST 201", name: "Atatürk İlkeleri ve İnkılap Tarihi I", term: "3. Dönem", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "TURK 201", name: "Türk Dili Dersleri I", term: "3. Dönem", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "HIST 203", name: "Türk Devrim Tarihi I (*)", term: "3. Dönem", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "TURK 203", name: "Uluslararası Öğrenciler İçin Türkçe I (*)", term: "3. Dönem", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "CENG 212", name: "Programlama Dilleri Kavramı", term: "4. Dönem", hours: "(3+0)", credits: "3", ects: "5" },
        { code: "CENG 214", name: "Mantık Tasarımı", term: "4. Dönem", hours: "(3+2)", credits: "4", ects: "6" },
        { code: "CENG 216", name: "Sayısal Hesaplama", term: "4. Dönem", hours: "(3+0)", credits: "3", ects: "5" },
        { code: "CENG 218", name: "Algoritmaların Analiz ve Tasarımı", term: "4. Dönem", hours: "(3+0)", credits: "3", ects: "5" },
        { code: "CENG 222", name: "Olasılık ve İstatistik", term: "4. Dönem", hours: "(3+0)", credits: "3", ects: "5" },
        { code: "HIST 202", name: "Atatürk İlkeleri ve İnkılap Tarihi II", term: "4. Dönem", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "TURK 202", name: "Türk Dili Dersleri II", term: "4. Dönem", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "HIST 204", name: "Türk Devrim Tarihi II (*)", term: "4. Dönem", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "TURK 204", name: "Uluslararası Öğrenciler İçin Türkçe II (*)", term: "4. Dönem", hours: "(2+0)", credits: "0", ects: "2" },
        { code: "CENG 311", name: "Bilgisayar Mimarisi", term: "5. Dönem", hours: "(3+2)", credits: "4", ects: "8", prereq: "CENG 214" },
        { code: "MAN 217", name: "Yönetimin Temelleri ve Liderlik", term: "5. Dönem", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 315", name: "Bilgi Yönetimi", term: "5. Dönem", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 465", name: "Designing Data-Intensive Systems", term: "5. Dönem", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "ART 240", name: "Resim Sanatı Kavramları ve Kuramları", term: "5. Dönem", hours: "(3+0)", credits: "3", ects: "3" },
        { code: "CENG 312", name: "Bilgisayar Ağları", term: "6. Dönem", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 316", name: "Yazılım Mühendisliği", term: "6. Dönem", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 318", name: "İnsan Bilgisayar Etkileşimi", term: "6. Dönem", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 322", name: "İşletim Sistemleri", term: "6. Dönem", hours: "(3+2)", credits: "4", ects: "8" },
        { code: "TS II", name: "Teknik Seçmeli II", term: "6. Dönem", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 411", name: "Bilgisayar Mühendisliğinde Profesyonellik", term: "7. Dönem", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 415", name: "Lisans Tezi ve Seminer I", term: "7. Dönem", hours: "(3+0)", credits: "3", ects: "8" },
        { code: "TS III", name: "Teknik Seçmeli III", term: "7. Dönem", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "TS IV", name: "Teknik Seçmeli IV", term: "7. Dönem", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "TOS II", name: "Teknik Olmayan Seçmeli II", term: "7. Dönem", hours: "(3+0)", credits: "3", ects: "3" },
        { code: "CENG 400", name: "Yaz Stajı", term: "7. Dönem", credits: "0", ects: "4" },
        { code: "SS II", name: "Sınırlı Seçmeli II", term: "8. Dönem", hours: "(3+0)", credits: "3", ects: "6", prereq: "CENG 415" },
        { code: "SS III", name: "Sınırlı Seçmeli III", term: "8. Dönem", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 416", name: "Lisans Tezi ve Seminer II", term: "8. Dönem", hours: "(3+0)", credits: "3", ects: "8", prereq: "CENG 415" },
        { code: "TS V", name: "Teknik Seçmeli V", term: "8. Dönem", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "TS VI", name: "Teknik Seçmeli VI", term: "8. Dönem", hours: "(3+0)", credits: "3", ects: "6" },
        { code: "CENG 323", name: "Proje Yönetimi", term: "Sınırlı Seçmeliler" },
        { code: "CENG 418", name: "Bilgi Güvenliği", term: "Sınırlı Seçmeliler" },
        { code: "CENG 424", name: "Gömülü Bilgisayar Sistemleri", term: "Sınırlı Seçmeliler" },
        { code: "CENG 370", name: "Ana Bilgisayarlar", term: "Teknik Seçmeliler · 3. Sınıf" },
        { code: "CENG 381", name: "Stokastik Süreçler", term: "Teknik Seçmeliler · 3. Sınıf" },
        { code: "CENG 382", name: "Bilgi Teorisi", term: "Teknik Seçmeliler · 3. Sınıf" },
        { code: "CENG 383", name: "Gerçek-Zamanlı Sistemler", term: "Teknik Seçmeliler · 3. Sınıf" },
        { code: "CENG 384", name: "Mikroişlemciler", term: "Teknik Seçmeliler · 3. Sınıf" },
        { code: "CENG 385", name: "Matematiksel Mantık", term: "Teknik Seçmeliler · 3. Sınıf" },
        { code: "CENG 386", name: "Bulanık Mantık Sistemleri", term: "Teknik Seçmeliler · 3. Sınıf" },
        { code: "CENG 388", name: "Web Programlama", term: "Teknik Seçmeliler · 3. Sınıf" },
        { code: "CENG 389", name: "Mobil Uygulama Geliştirme", term: "Teknik Seçmeliler · 3. Sınıf" },
        { code: "CENG 390", name: "Bulut Bilişim", term: "Teknik Seçmeliler · 3. Sınıf" },
        { code: "CENG 391", name: "İmge Anlamaya Giriş", term: "Teknik Seçmeliler · 3. Sınıf" },
        { code: "CENG 421", name: "Bilgisayar Ağı Programlama", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 422", name: "Bilgisayar Ağı Tasarımı ve Yönetimi", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 431", name: "Yazılım Sistemleri Geliştirilmesi", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 432", name: "Kurumsal Uygulama Geliştirmenin Temelleri", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 433", name: "İnternet için Ölçeklenebilir Yazılım Geliştirme", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 434", name: "Kurumsal Uygulama Entegrasyonları", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 435", name: "Veritabanı Yönetim Sistemi Tasarımı ve Gerçekleştirilmesi", term: "Teknik Seçmeliler · 4. Sınıf", prereq: "CENG 315" },
        { code: "CENG 436", name: "Dağıtık Bilgi Yönetimi", term: "Teknik Seçmeliler · 4. Sınıf", prereq: "CENG 315" },
        { code: "CENG 437", name: "Yazılım Kalite Yönetimi", term: "Teknik Seçmeliler · 4. Sınıf", prereq: "CENG 316" },
        { code: "CENG 441", name: "Paralel Programlamaya Giriş", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 442", name: "Çok Çekirdekli Mimariler ve İşletim Sistemleri", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 443", name: "Heterojen Paralel Programlama", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 444", name: "Paralel Programlama Örüntüleri", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 451", name: "İleri Sayısal Sistem Tasarımı", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 452", name: "Gömülü Sistemler için Yazılım Geliştirilmesi", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 461", name: "Yapay Zeka", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 462", name: "Esnek Hesaplama", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 463", name: "Yapay Öğrenmeye Giriş", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 464", name: "Metin Madenciliği", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 465", name: "Veri-Yoğun Sistemlerin İlkeleri", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 467", name: "Doğal Dil Anlama ve Üretme", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 471", name: "Kriptografi", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 472", name: "Bilgisayar Ağı Güvenliği", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 473", name: "Bilgi ve İletişim Teknolojileri Güvenliği", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 481", name: "Bilgisayar Bilimlerinde Kuramsal Yaklaşımlar", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 482", name: "Evrimsel Hesaplama", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 483", name: "Davranışsal Robot Bilimi", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 484", name: "Veri Madenciliği", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 485", name: "Bilgi Teknolojilerinde Girişimcilik", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 486", name: "Akıllı İşletmeler için Girişimcilik", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 487", name: "Bilgisayar Grafiğine Giriş", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 488", name: "Bilgisayar Grafiği", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 491", name: "Destekleyici Alan Dersi", term: "Teknik Seçmeliler · 4. Sınıf" },
        { code: "CENG 499", name: "Ortak Eğitim (COOP)", term: "Teknik Seçmeliler · 4. Sınıf" },
      ],
      learningLabel: "Şu an öğrendiklerim",
      learning: [
        "Postgres logical replication",
        "pgvector ile vektör arama",
        "Linear sync engine",
        "MCP sunucu desenleri",
        "Cloudflare Durable Objects",
        "Olasılıksal veri yapıları",
        "Postgres logical replication",
      ],
    },
    playground: {
      eyebrow: "Atölye",
      h: "Küçük bir atölye. Mod değiştir.",
      lede:
        "Editöryal site sönümleniyor ve sayfa bir alete dönüşüyor. Her modül önce kendim için yaptığım bir şey; siz de oynayabilirsiniz.",
      ports: {
        title: "ports — proje farkındalıklı lsof",
        desc: "macOS için yazdığım küçük bir Go CLI. Hangi dev projenin hangi portu dinlediğini, ne kadar süredir çalıştığını gösterir; port numarasıyla kill, pause, resume yapmana izin verir. Sıralama modlarını dene.",
        foot: "Tek dosyalık Go · MIT · v0.3.0 ·",
      },
      sql: {
        title: "Portfolyo SQL",
        desc: "Bu sitenin küçük, salt-okunur veritabanı. \\d, \\d projects veya bölümlere SELECT sorguları dene.",
        foot: "salt-okunur parser · dene: select * from projects",
      },
      repl: {
        title: "Postgres replikasyonu, görünür",
        desc: "Primary commit, WAL aktarımı, replica yetişiyor. Gecikme görebileceğin bir özellik.",
        foot: "CENG 465'e bağlı · ortalama gecikme 0.4s",
      },
      term: {
        title: "Terminal",
        desc: "Sitenin herhangi bir yerinde ~ tuşuna bas. Birkaç dürüst komut.",
        foot: "tilde (~) ile aç · esc ile kapat",
      },
    },
    writing: {
      eyebrow: "Yazılar",
      h: "Notlar, blog değil.",
      empty: "Şu an bilerek boş.",
      emptyDesc:
        "Burada bayat 'temiz kod' fikirleri yerine hiçbir şey olmasını tercih ederim. İlk yazı söyleyecek bir şeyim olduğunda gelir — büyük ihtimalle esnek kodun zekice koddan neden daha değerli olduğuna, testin üretimde kirasını nasıl ödediğine, Postgres replikasyonuna ve MCP'nin dağınık tarafına dair.",
      cta: "Çıkınca haber ver",
    },
    contact: {
      bigTop: "Bilmem gereken",
      bigBottom: "bir şey üstünde mi çalışıyorsun?",
      email: "hi@erdm.io",
      socials: { gh: "github/erdemylmaz", li: "linkedin/erdem-yılmaz", ig: "instagram/erdemyilmaz.x" },
      socialsHref: {
        gh: "https://github.com/erdemylmaz",
        li: "https://www.linkedin.com/in/erdem-y%C4%B1lmaz-b497921a8/",
        ig: "https://www.instagram.com/erdemyilmaz.x/",
      },
      colophon: "İzmir, kampüs ve arada bir uzun yol arasında.",
      now: "Devredin'de yazılım · benzersor kurucu ortak · İYTE'de CS",
    },
  },
};

export const useT = (lang: Lang) => CONTENT[lang] ?? CONTENT.en;
